Repository ISPP-07/htld-doc, pull requests merged in 2024-05, with the labels that each got.

#383 fix: Fix user manual images to match deployment
  docs/07. Manuales de usuario/7.3. Software Reviewer Guideline - Sprint 3.mdx
  static/img/usermanual/sprint3/acat-beneficiariodetalle.png
  static/img/usermanual/sprint3/acat-beneficiarioedit.png
  static/img/usermanual/sprint3/acat-beneficiarios.png
  static/img/usermanual/sprint3/acat-finalizados.png
  static/img/usermanual/sprint3/acat-intervenciondetalle.png
  static/img/usermanual/sprint3/acat-intervenciones.png
  static/img/usermanual/sprint3/acat-users.png
  static/img/usermanual/sprint3/cyc-almacenes.png
  static/img/usermanual/sprint3/cyc-entregas.png
  static/img/usermanual/sprint3/cyc-estadisticascontraste.png
  static/img/usermanual/sprint3/cyc-estadisticasnormal.png
  static/img/usermanual/sprint3/cyc-familiadetalle.png
  static/img/usermanual/sprint3/cyc-familiaedit.png
  static/img/usermanual/sprint3/cyc-familias.png
  static/img/usermanual/sprint3/cyc-inventario.png
  static/img/usermanual/sprint3/cyc-inventariodetalle.png
  static/img/usermanual/sprint3/cyc-users.png
  static/img/usermanual/sprint3/usuariodetalle.png
  static/img/usermanual/sprint3/usuarioedit.png
  static/img/usermanual/sprint3/usuarioform.png
Labels: Spain

#384 doc: Create the story of the PPL #381
  docs/06. Recursos/6.1. Presentaciones/6.1.8. 07-05-2024.md
Labels: Beti

#378 doc: calculated ROI for the business model
  docs/03. Planificación/Modelo de negocio.mdx
Labels: Xtreme

#389 doc: Future work section
  docs/06. Recursos/6.6. Trabajo futuro.mdx
Labels: Spain

#395 Update the information provided by pilots users #391
  docs/04. Seguimiento/4.12. Registro de cambios.mdx
  docs/04. Seguimiento/4.7. InformationProvidedByPilotUsers.mdx
  docs/04. Seguimiento/4.8. MinimumInformationFromPilotUsers_GatheredByForm.mdx
  docs/Entrega.md
Labels: Spain

#394 Update BGC
  docs/Anexo I. Aportación a la BGCC/Semana 1.md
  docs/Anexo I. Aportación a la BGCC/Semana 10.md
  docs/Anexo I. Aportación a la BGCC/Semana 11.md
  docs/Anexo I. Aportación a la BGCC/Semana 2.md
  docs/Anexo I. Aportación a la BGCC/Semana 3.md
  docs/Anexo I. Aportación a la BGCC/Semana 4.md
  docs/Anexo I. Aportación a la BGCC/Semana 5.md
  docs/Anexo I. Aportación a la BGCC/Semana 6.md
  docs/Anexo I. Aportación a la BGCC/Semana 7.md
  docs/Anexo I. Aportación a la BGCC/Semana 8.md
  docs/Anexo I. Aportación a la BGCC/Semana 9.md
Labels: Spain, Waiting for Review

#398 doc: Add personas section #397
  docs/03. Planificación/Personas.md
  static/img/personas/Eduardo.png
  static/img/personas/Ines.png
Labels: Xtreme

#400 doc: updated use of AI in PPL
  docs/Anexo II. Uso de la IA/Registro de uso de IA Semana 11.md
  docs/Anexo II. Uso de la IA/Registro de uso de IA Semana 12.md
Labels: Xtreme

#401 doc: updated graphs to PPL
  docs/04. Seguimiento/4.3. Seguimiento de costes/Estado del proyecto.mdx
  docs/04. Seguimiento/4.4. Burndown.mdx
  static/img/graphs/burndown_PPL.png
  static/img/graphs/projectStatus_PPL_week11.png
  static/img/graphs/projectStatus_PPL_week12.png
Labels: Xtreme

#409 Update 5.4. PilotUsersPerformanceEvaluation.mdx
  docs/05. Rendimiento/5.4. PilotUsersPerformanceEvaluation.mdx
Labels: Spain

#411 Doc/410 doc update pilot user ca
  docs/02. Acuerdos y contratos/2.3. Acuerdo de compromiso de usuarios piloto.mdx
  static/docs/CAPU_Carlos_Bermejo.pdf
  static/docs/CAPU_Javier_Fernández.pdf
  static/docs/CAPU_Manuel_Otero.pdf
  static/docs/CAPU_Mario_Izquierdo.pdf
Labels: Spain

#434 doc: PPL User manual
  docs/07. Manuales de usuario/7.4. Software Reviewer Guideline - PPL.mdx
  docs/07. Manuales de usuario/7.5. Manuales de Uso.mdx
  static/img/usermanual/ppl/acat-beneficiarios.png
  static/img/usermanual/ppl/acat-intervenciones.png
  static/img/usermanual/ppl/cyc-almacenes.png
  static/img/usermanual/ppl/cyc-entregas.png
  static/img/usermanual/ppl/cyc-familiaform2.png
  static/img/usermanual/ppl/cyc-familias.png
  static/img/usermanual/ppl/cyc-inventario.png
Labels: Spain

#406 doc: Add presentation script part 2 #404
  docs/06. Recursos/6.1. Presentaciones/6.1.8. 07-05-2024.md
  static/img/pptxPPL/accionesCM.png
  static/img/pptxPPL/accionesPPL.png
  static/img/pptxPPL/backups.png
  static/img/pptxPPL/fin.png
  static/img/pptxPPL/gdpr.png
  static/img/pptxPPL/huellaCarbono.png
  static/img/pptxPPL/ia.png
  static/img/pptxPPL/ideasCM.png
  static/img/pptxPPL/marketingPPL.png
  static/img/pptxPPL/personas.png
  static/img/pptxPPL/planificacionCM.png
  static/img/pptxPPL/postLanzamiento.png
  static/img/pptxPPL/proveedores.png
  static/img/pptxPPL/secciones.png
  static/img/pptxPPL/segmentacion.png
Labels: Xtreme

#453 doc: project status update at week 13
  docs/04. Seguimiento/4.3. Seguimiento de costes/Estado del proyecto.mdx
  static/img/graphs/projectStatus_WPL_week13.png
Labels: Xtreme

#458 Update Marketing doc
  docs/03. Planificación/3.3. Marketing/3.11. Campaña de lanzamiento.mdx
Labels: Spain

#479 doc: update of the graphs for the WPL
  docs/04. Seguimiento/4.3. Seguimiento de costes/Estado del proyecto.mdx
  docs/04. Seguimiento/4.4. Burndown.mdx
  static/img/graphs/burndown_WPL.png
  static/img/graphs/projectStatus_WPL_week15.png
Labels: Xtreme

#486 doc: Update Software reviewer guideline
  docs/07. Manuales de usuario/7.5. Software Reviewer Guideline - WPL.mdx
  docs/07. Manuales de usuario/7.6. Manuales de Uso.mdx
  docs/07. Manuales de usuario/7.7. Deployment Manual.mdx
  docs/Entrega.md
Labels: Spain

#488 doc: update performance for WPL
  docs/05. Rendimiento/5.3. PerformanceEvaluation.mdx
Labels: Beti

#496 doc: Add Harmony videos #492
  docs/06. Recursos/6.6. Vídeos/Anuncio para inversores.md
  docs/06. Recursos/6.6. Vídeos/Anuncio usuarios.md
  docs/06. Recursos/6.6. Vídeos/Demo Cirio y Costal.md
  docs/06. Recursos/6.6. Vídeos/_category_.json
Labels: Spain, Waiting for Review
