Repository ISPP-07/htld-doc, pull requests merged in 2024-03, with the labels that each got.

#112 Doc/87 acceptance criteria and uc
  .gitignore
  docs/Información del servicio/Casos de uso.mdx
  docs/Información del servicio/Criterios de aceptación.mdx
  docs/Información del servicio/_category_.json
Labels: Waiting for Review

#110 Improve TCO
  docs/Coste total de la propiedad/TCO.mdx
  docs/Coste total de la propiedad/_category_.json
  static/img/tco/comparativa-precios.png
  static/img/tco/databases-prices.png
  static/img/tco/engine-despliegue.png
  static/img/tco/engine-environment.png
  static/img/tco/engine-instancia-b.png
  static/img/tco/engine-instancia-f.png
  static/img/tco/estimacion-de-coste-de-desarrollo.png
  static/img/tco/github-actions.png
  static/img/tco/github-precios.png
  static/img/tco/row-reads.png
  static/img/tco/vercel-table.png
Labels: Beti

#116 doc: Lessons learnt
  docs/Lecciones aprendidas/Lecciones aprendidas.mdx
  docs/Lecciones aprendidas/_category_.json
Labels: Beti

#111 Added documentation directory, and changes logs
  docs/Documentación/07-Registro-de-Cambios.mdx
  docs/Documentación/_category.json
  docs/Documentación/plantilla-registro-de-cambios.mdx
  yarn.lock
Labels: Waiting for Review

#115 doc: Problems register
  docs/Registro de problemas/Problemas encontrados.mdx
  docs/Registro de problemas/_category_.json
Labels: Beti

#132 doc: Added the analysis document of alternatives to docusaurus
  docs/Análisis de alternativas/Backend/Frameworks y CRMs.mdx
  docs/Análisis de alternativas/Backend/Herramientas.mdx
  docs/Análisis de alternativas/Despliegue/Alternativas de despliegue.mdx
  docs/Análisis de alternativas/Frontend/Bibliotecas.mdx
  docs/Análisis de alternativas/Frontend/Frameworks de CSS.mdx
  docs/Análisis de alternativas/Frontend/Frameworks de código.mdx
  docs/Análisis de alternativas/Frontend/Herramientas de código.mdx
  docs/Análisis de alternativas/Frontend/Herramientas de mockups.mdx
  docs/Análisis de alternativas/Frontend/Lenguajes.mdx
  docs/Análisis de alternativas/Información.mdx
  docs/Análisis de alternativas/Tecnologías finales.mdx
  docs/Análisis de alternativas/_category_.json
  static/img/analysis alternatives/backend.png
  static/img/analysis alternatives/despliegue.png
  static/img/analysis alternatives/frontend.png
  static/img/analysis alternatives/mockups.png
Labels: Xtreme

#136 conf: Create stats script
  .github/workflows/update-stats.yml
  .prettierignore
  docs/Seguimiento del equipo/Estadísticas de github.mdx
  package-lock.json
  package.json
  src/components/stats/stats.mjs
  yarn.lock
Labels: Xtreme

#139 doc: improve and fill team performance
  docs/Seguimiento del equipo/Medición del rendimiento.mdx
  static/img/performance/new-formula.png
Labels: Beti

#140 Doc/130 doc retrospective presentation
  docs/Presentaciones/12-05-2024.md
Labels: Spain

#160 Doc/151 doc legal aspects of the project
  docs/Legal/Customer Agreement.mdx
  docs/Legal/Data Protection.mdx
  docs/Legal/Licensing Agreement.mdx
  docs/Legal/_category_.json
Labels: Spain

#157 doc:Add story board
  docs/Información del servicio/Story board.mdx
  static/img/storyBoard/Cell-Row-0-Col-0.png
  static/img/storyBoard/Cell-Row-0-Col-1.png
  static/img/storyBoard/Cell-Row-0-Col-2.png
  static/img/storyBoard/Cell-Row-0-Col-3.png
  static/img/storyBoard/Cell-Row-0-Col-4.png
  static/img/storyBoard/Cell-Row-0-Col-5.png
  static/img/storyBoard/Cell-Row-0-Col-6.png
  static/img/storyBoard/Cell-Row-0-Col-7.png
  static/img/storyBoard/Cell-Row-0-Col-8.png
  static/img/storyBoard/Cell-Row-1-Col-0.png
  static/img/storyBoard/Cell-Row-1-Col-1.png
  static/img/storyBoard/Cell-Row-1-Col-2.png
  static/img/storyBoard/Cell-Row-1-Col-3.png
  static/img/storyBoard/Cell-Row-1-Col-4.png
  static/img/storyBoard/Cell-Row-1-Col-5.png
  static/img/storyBoard/Cell-Row-1-Col-6.png
  static/img/storyBoard/Cell-Row-1-Col-7.png
  static/img/storyBoard/Cell-Row-1-Col-8.png
  yarn.lock
Labels: Spain

#165 Doc/152 update on cost monitoring
  docs/Coste total de la propiedad/TCO.mdx
Labels: Beti

#138 doc: Added the notes of the theory pills
  docs/Apuntes pildoras teoricas/Theory Pill - Replanning, Story Boards and Estimation of Expenses_Income.mdx
  docs/Apuntes pildoras teoricas/Theory Pill - Testing.mdx
  docs/Apuntes pildoras teoricas/Theory Pill - customer_agreement.mdx
  static/img/Theory Pills/TP_Cycle_Time_Chart.png
  static/img/Theory Pills/TP_GQM.png
  static/img/Theory Pills/TP_costesVSbeneficios.png
  static/img/Theory Pills/TP_design.png
  static/img/Theory Pills/TP_estimaciones.png
  static/img/Theory Pills/TP_montecarlos.png
  static/img/Theory Pills/TP_montecarlos2.png
  static/img/Theory Pills/TP_presupuesto_puntoshHistoria.png
  static/img/Theory Pills/TP_storyboard.png
  static/img/Theory Pills/TP_terminos_condiciones.png
  static/img/Theory Pills/TP_test_granularidad.png
  static/img/Theory Pills/TP_test_int_ejemplos.png
Labels: Xtreme

#195 doc: Pilot user document
  docs/Gestion de Usuarios Piloto/Pilots.mdx
  docs/Gestion de Usuarios Piloto/_category_.json
  static/img/calendar/April.png
  static/img/calendar/March.png
  static/img/calendar/May.png
Labels: Spain

#185 doc/Pilot User CA
  docs/Gestion de Usuarios Piloto/Acuerdo de compromiso de usuarios piloto.md
Labels: Spain

#198 doc: new replanification and planification
  docs/Planificación/Replanificación 2.mdx
  static/img/planification/gantt-2.png
  static/img/planification/plan-2.png
Labels: Beti

#193 Doc/173 add individual evaluation docusaurus
  docs/Seguimiento del equipo/Acuerdo de compromiso.mdx
  docs/Seguimiento del equipo/PerformanceEvaluation.mdx
Labels: Xtreme

#196 doc: Added the graphs on the progress of the project
  docs/Estimación de gastos e ingresos/Estimación de gastos e ingresos.md
  docs/Seguimiento de los costes/Estado del proyecto.mdx
  docs/Seguimiento del equipo/Burndown.mdx
  static/img/graphs/beneficiosvscostes.png
  static/img/graphs/burndown_sprin2.png
  static/img/graphs/estadoDelProyecto_sprint2.png
Labels: Xtreme

#200 doc: update tco
  docs/Coste total de la propiedad/TCO.mdx
  static/img/tco/sendgrid.png
Labels: Beti

#205 doc: Added backend handbook #183
  docs/Gestión del desarrollo/Manual de desarrollo de backend.md
  docs/Gestión del desarrollo/_category.json
  static/img/backendHandbook/development-diagram.png
  static/img/backendHandbook/tests-structure.png
Labels: Xtreme

#194 Doc/172 pilot user provided information
  docs/Documentación/07-Registro-de-Cambios.mdx
  docs/Documentación/_category.json
  docs/Documentación/plantilla-registro-de-cambios.mdx
  docs/Gestion de Usuarios Piloto/InformationProvidedByPilotUsers.mdx
  docs/Gestion de Usuarios Piloto/PerformanceEvaluation.mdx
  docs/Gestion de Usuarios Piloto/Registro de cambios.mdx
Labels: Xtreme

#214 Doc/167 improve and update individual performance
  docs/Seguimiento del equipo/Medición del rendimiento.mdx
  static/img/performance/graph-performance.png
  static/img/performance/qa-performance.png
Labels: Beti

#216 doc: Create quality follow-up section #206
  docs/Estadísticas del grupo/_category_.json
  docs/Seguimiento del equipo/Registro semana 1.md
  docs/Seguimiento del equipo/Registro semana 2.md
  docs/Seguimiento del equipo/Registro semana 3.md
  docs/Seguimiento del equipo/Registro semana 4.md
  docs/Seguimiento del equipo/Registro semana 5.md
  docs/Seguimiento del equipo/Seguimiento de la calidad.md
  static/img/coverage/ACATcoverage.png
  static/img/coverage/backCoverage.png
  static/img/coverage/coverage.png
  static/img/coverage/coverageACAT2.png
  static/img/coverage/coverageBack2.png
  static/img/coverage/coverageCyC2.png
  static/img/coverage/cycCoverage.png
  static/img/quality/ACATQ.png
  static/img/quality/ACATQ2.png
  static/img/quality/CyCQ.png
  static/img/quality/CyCQ2.png
  static/img/quality/Q.png
  static/img/quality/backQ.png
  static/img/quality/backQ2.png
Labels: Xtreme

#218 Doc/174 doc presentation and script 12
  docs/Presentaciones/02-04-2024.md
  docs/Presentaciones/03-03-2024.mdx
  docs/Presentaciones/12-03-2024.md
  docs/Presentaciones/19-03-2024.md
  static/img/graphs/burndown_sprin2.png
Labels: Spain
