Repository ISPP-07/htld-doc, pull requests merged in 2024-04, with the labels that each got.

#197 doc: Added metric for the quality of the solution
  docs/Registro de problemas/Problemas encontrados.mdx
Labels: Xtreme

#240 doc: Sprint 2 User Manual
  docs/Gestion de Usuarios Piloto/Software Reviewer Guideline - Sprint 2.mdx
  static/img/usermanual/sprint2/acat-beneficiariodelete.png
  static/img/usermanual/sprint2/acat-beneficiariodetalle.png
  static/img/usermanual/sprint2/acat-beneficiarioedit.png
  static/img/usermanual/sprint2/acat-beneficiarioform.png
  static/img/usermanual/sprint2/acat-beneficiarios.png
  static/img/usermanual/sprint2/acat-export.png
  static/img/usermanual/sprint2/acat-finalizados.png
  static/img/usermanual/sprint2/acat-intervenciondetalle.png
  static/img/usermanual/sprint2/acat-intervenciones.png
  static/img/usermanual/sprint2/acat-intervencionform.png
  static/img/usermanual/sprint2/acat-login.png
  static/img/usermanual/sprint2/acat-sidebar.png
  static/img/usermanual/sprint2/cambiarcontr.png
  static/img/usermanual/sprint2/cyc-almacenes.png
  static/img/usermanual/sprint2/cyc-almacenform.png
  static/img/usermanual/sprint2/cyc-entregaform.png
  static/img/usermanual/sprint2/cyc-entregas.png
  static/img/usermanual/sprint2/cyc-familiadetalle.png
  static/img/usermanual/sprint2/cyc-familiaform1.png
  static/img/usermanual/sprint2/cyc-familiaform2.png
  static/img/usermanual/sprint2/cyc-familias.png
  static/img/usermanual/sprint2/cyc-home.png
  static/img/usermanual/sprint2/cyc-inventario.png
  static/img/usermanual/sprint2/cyc-inventariodetalle.png
  static/img/usermanual/sprint2/cyc-inventarioform.png
  static/img/usermanual/sprint2/restaurar.png
  static/img/usermanual/sprint2/usuarioboton.png
  static/img/usermanual/sprint2/usuariodetalle.png
  static/img/usermanual/sprint2/usuarioedit.png
  static/img/usermanual/sprint2/usuarioform.png
  static/img/usermanual/sprint2/usuarios.png
Labels: Spain

#246 fix: User manual credentials
  docs/Gestion de Usuarios Piloto/Software Reviewer Guideline - Sprint 2.mdx
Labels: Spain

#265 doc: Added improve ROI chart
  static/img/graphs/beneficiosvscostes.png
Labels: Spain

#266 doc: Added color to priority column
  docs/04. Seguimiento/4.8. Registro de cambios.mdx
Labels: Spain

#268 Doc/257 add ppl planning
  docs/03. Planificación/3.4. Planificación Inicial.mdx
  docs/03. Planificación/3.5. Replanificación 1.mdx
  docs/03. Planificación/3.5. Replanificación.mdx
  docs/03. Planificación/3.6. Criterios de aceptación.mdx
  docs/03. Planificación/3.6. Replanificación 2.mdx
  docs/03. Planificación/3.7. Estimación de gastos e ingresos.md
  src/pages/index.js
Labels: Beti

#267 Doc/264 update tco
  docs/03. Planificación/3.8. TCO.mdx
  static/img/tco/aws 2.png
  static/img/tco/aws.png
  static/img/tco/comparativa-precios.png
Labels: Beti

#259 doc: Updated project status graph
  docs/04. Seguimiento/4.3. Seguimiento de costes/Estado del proyecto.mdx
  static/img/graphs/estadoDelProyecto_sprint3_semana9.png
Labels: Xtreme

#261 doc: Updated week 9 compliance in the CA
  docs/02. Acuerdos y contratos/2.1. Acuerdo de compromiso.mdx
Labels: Xtreme

#274 doc: added notes by Theoy Pill on GDPR and UX
  docs/06. Recursos/6.2. Apuntes pildoras teoricas/Theory Pill on GDPR and UX.mdx
Labels: Xtreme

#281 Doc/273 change self assesment to boolean
  docs/05. Rendimiento/5.1. Autoevaluación/Sprint 1.md
  docs/05. Rendimiento/5.1. Autoevaluación/Sprint 2.md
Labels: Spain

#276 Doc/253 presentation and script 2
  docs/06. Recursos/6.1. Presentaciones/6.1.5. 09-04-2024.md
Labels: Xtreme

#295 doc: added burndown sprint 3
  docs/04. Seguimiento/4.4. Burndown.mdx
  static/img/graphs/burndown_sprint3.png
Labels: Xtreme

#301 doc: added sprint 3 project status chart
  docs/04. Seguimiento/4.3. Seguimiento de costes/Estado del proyecto.mdx
  static/img/graphs/estadoDelProyecto_sprint2.png
  static/img/graphs/estadoDelProyecto_sprint3.png
  static/img/graphs/estadoDelProyecto_sprint3_semana9.png
Labels: Xtreme

#299 doc: Update problem management
  docs/04. Seguimiento/4.9. Problemas encontrados.mdx
Labels: Spain

#290 doc: Update the information provided by pilot users
  docs/04. Seguimiento/4.7. InformationProvidedByPilotUsers.mdx
  docs/04. Seguimiento/4.8. Registro de cambios.mdx
Labels: Spain

#287 doc: Update S3 and PPL planning #286
  docs/03. Planificación/3.5. Replanificación.mdx
Labels: Beti

#293 Doc/288 update tco
  docs/03. Planificación/3.8. TCO.mdx
  static/img/tco/ss.png
Labels: Beti

#302 Doc/296 killer opener and story
  docs/06. Recursos/6.1. Presentaciones/6.1.6. 23-04-2024.md
Labels: Beti

#305 doc: Add W9 feedback
  docs/Anexo I. Aportación a la BGCC/Semana 9.md
Labels: Beti, Waiting for Review

#325 doc: add new performance marks
  docs/05. Rendimiento/5.2. Medición del rendimiento.mdx
  static/img/performance/Analista.png
  static/img/performance/Marketing.png
Labels: Beti

#310 docs: Add 23rd April presentation script
  docs/06. Recursos/6.1. Presentaciones/6.1.6. 23-04-2024.md
  static/img/pptxSprint3/anuncio1.png
  static/img/pptxSprint3/anuncio2.png
  static/img/pptxSprint3/burndown.png
  static/img/pptxSprint3/ca1.png
  static/img/pptxSprint3/ca2.png
  static/img/pptxSprint3/ca3.png
  static/img/pptxSprint3/calidad.png
  static/img/pptxSprint3/changelog.png
  static/img/pptxSprint3/competidores.png
  static/img/pptxSprint3/contexto.png
  static/img/pptxSprint3/demo.png
  static/img/pptxSprint3/estadoActual.png
  static/img/pptxSprint3/fin.png
  static/img/pptxSprint3/huellaCarbono.png
  static/img/pptxSprint3/ia.png
  static/img/pptxSprint3/legalidad.png
  static/img/pptxSprint3/marketing.png
  static/img/pptxSprint3/openSource.png
  static/img/pptxSprint3/opener1.png
  static/img/pptxSprint3/opener2.png
  static/img/pptxSprint3/planificacionPpl.png
  static/img/pptxSprint3/portada.png
  static/img/pptxSprint3/problemas.png
  static/img/pptxSprint3/reloj1.png
  static/img/pptxSprint3/reloj2.png
  static/img/pptxSprint3/rendimiento.png
  static/img/pptxSprint3/replanificacion.png
  static/img/pptxSprint3/resultados.png
  static/img/pptxSprint3/roi.png
  static/img/pptxSprint3/roles.png
  static/img/pptxSprint3/secciones.png
  static/img/pptxSprint3/tco.png
  static/img/pptxSprint3/tests.png
  static/img/pptxSprint3/testsCarga.png
  static/img/pptxSprint3/upCa1.png
  static/img/pptxSprint3/upCa2.png
  static/img/pptxSprint3/upCalendario1.png
  static/img/pptxSprint3/upCalendario2.png
  static/img/pptxSprint3/upEstado.png
  static/img/pptxSprint3/upFeedback.png
Labels: Xtreme

#356 doc: writing the business model
  docs/03. Planificación/Modelo de negocio.mdx
Labels: Xtreme

#362 doc: added the theoretical pill notes for week 12
  docs/06. Recursos/6.2. Apuntes pildoras teoricas/Theory pill on market segmentation, traction, and community management.mdx
  static/img/Theory Pills/TP_content_plan.png
  static/img/Theory Pills/TP_hype_cycle.png
  static/img/Theory Pills/TP_list_potencial_segments.png
  static/img/Theory Pills/TP_potencial_segments_table.png
  static/img/Theory Pills/TP_segmentation.png
  static/img/Theory Pills/TP_steps_content_creator.png
  static/img/Theory Pills/TP_voice_vs_tone.png
Labels: Xtreme

#377 doc: add youtube videos iframes
  docs/07. Manuales de usuario/7.4. Manuales de Uso.mdx
Labels: Beti
